EnableImagePreviewing: false
themes:
  - name: "green"
    colors:
      - "#eacacb"
      - "#cee1e6"
      - "#d8c8b1"
      - "#f9fbf0"
      - "#E2EFBE"
      - "#c2dca9"
      - "#a0c897"
      - "#7eb587"
      - "#5ba27a"
      - "#328f6f"
      - "#22493B"
      - "#172B23"
      - "#0B1310"

  - name: "red"
    colors:
      - "#c8dab6"
      - "#bedad9"
      - "#c9b2db"
      - "#f2b0a9"
      - "#d04949"
      - "#b84046"
      - "#a03842"
      - "#89303c"
      - "#722a36"
      - "#5b232e"
      - "#451d26"
      - "#30161c"
      - "#1c0f12"

  - name: "blue"
    colors:
      - "#f3e9fc"
      - "#fce9e9"
      - "#f2fce9"
      - "#d3f7f8"
      - "#c5f0f2"
      - "#b8e8ec"
      - "#aae1e6"
      - "#9cd9e0"
      - "#8ed2db"
      - "#80cad6"
      - "#71c3d1"
      - "#62bbcd"
      - "#51b4c8"
      - "#4ba3b5"
      - "#4592a2"
      - "#3f8190"
      - "#38707e"
      - "#32616c"
      - "#2c515b"
      - "#25424a"
      - "#1f343a"
      - "#18262a"

  - name: "purple"
    colors:
      - "#14013c"
      - "#1b0941"
      - "#230e45"
      - "#2b134a"
      - "#33184f"
      - "#3a1d54"
      - "#422359"
      - "#4a295e"
      - "#512e63"
      - "#593468"
      - "#603a6d"
      - "#684072"
