themes:
  - name: "green"
    colors:
      - "#eacacb"
      - "#cee1e6"
      - "#d8c8b1"
      - "#f9fbf0"
      - "#E2EFBE"
      - "#c2dca9"
      - "#a0c897"
      - "#7eb587"
      - "#5ba27a"
      - "#328f6f"
      - "#22493B"
      - "#172B23"
      - "#0B1310"
      - "#000000"

  - name: "red"
    colors:
      - "#c8dab6"
      - "#bedad9"
      - "#c9b2db"
      - "#e9e2e4"
      - "#8a0a0c"
      - "#840613"
      - "#7d0519"
      - "#76061d"
      - "#6e0820"
      - "#660b23"
      - "#5d0e25"
      - "#551125"
      - "#4c1326"
      - "#431425"
      - "#281018"
      - "#000000"