themes:
  - name: "main"
    colors:
      - "#eacacb"
      - "#cee1e6"
      - "#d8c8b1"
      - "#f9fbf0"
      - "#E2EFBE"
      - "#c2dca9"
      - "#a0c897"
      - "#7eb587"
      - "#5ba27a"
      - "#328f6f"
      - "#22493B"
      - "#172B23"
      - "#0B1310"
      - "#000000"
